apiVersion: v1
kind: Service
metadata:
  labels:
    run: testpod
  name: my-service
spec:
  ports:
  - port: 80          # port on service
    protocol: TCP     # targets the TCP (default) port 9376 on the pod
    targetPort: 9376    # port on pod that svc forwards requests to
    nodePort: 30008   # port on Node (30000-32767)
  selector:
    run: testpod
  type: NodePort      # exposes port on Node
status:
  loadBalancer: {}
